MainApp/urls.py
from django.urls import path
from .views import*

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', FirstView.as_view(), name='first-view'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),



    path('post/', PostView.as_view(), name='post-view'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail-view'),
    path('add-post/', AddPostView.as_view(), name='add-post'),
    path('post/edit/<int:pk>/', UpdatePostView.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', DeletePostView.as_view(), name='delete-post'),

    path('add-course/', AddCourseView.as_view(), name='add-course'),
    path('course/list/', CourseListView.as_view(), name='course-list'),
    path('course/<str:cats>/', course_view, name='course-view'),


    path('notes/', NotesView.as_view(), name='notes-view'),
    path('notes/<int:pk>/', NotesDetailView.as_view(), name='notes_detail-view'),
    path('add-notes/', AddNotesView.as_view(), name='add-notes'),
    path('notes/edit/<int:pk>/', UpdateNotesView.as_view(), name='update-notes'),
    path('notes/<int:pk>/delete/', DeleteNotesView.as_view(), name='delete-notes'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Accounts.urls')),
    path('', include('MainApp.urls')),
]

Accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    is_admin = models.BooleanField('Is admin', default=False)
    is_cr = models.BooleanField('Is cr', default=False)
    is_student = models.BooleanField('Is student', default=True)

    middle_name = models.CharField('Middle name', max_length=255, null=True)
    registration_number = models.CharField('Registration number', max_length=255, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    
   


    # Set custom related names for permissions and groups
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_permissions',
        related_query_name='user',
    )
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name='custom_user_groups',
        related_query_name='user',
    )

MainApp/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

class Course(models.Model):
	course_name = models.CharField(max_length=255)
	course_code = models.CharField(max_length=255)
	lecture_teacher = models.CharField(max_length=255, blank=True)
	practical_teacher = models.CharField(max_length=255, blank=True)

	def __str__(self):
		return self.course_name

	def get_absolute_url(self):
		return reverse('dashboard')
#		return reverse('dashboard', args=(str(self.id)))

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=255)
	body = RichTextField(null=True, blank=True)
	#body = models.TextField(null=True, blank=True)
	post_date = models.DateField(auto_now_add=True)
	post_image = models.ImageField(null=True, blank=True, upload_to="images/")
	post_file = models.FileField(null=True, blank=True, upload_to="documents/")



	def get_absolute_url(self):
		return reverse('post_detail-view', args=(str(self.id)))


class Notes(models.Model):
	title = models.CharField(max_length=255)
	#body = models.TextField(null=True, blank=True)
	body = RichTextField(null=True, blank=True)
	notes_date = models.DateField(auto_now_add=True)
	course = models.CharField(max_length=300, default='Unknown')
	header_image = models.ImageField(null=True, blank=True, upload_to="images/")
	header_file = models.FileField(null=True, blank=True, upload_to="documents/")


	def get_absolute_url(self):
		return reverse('notes_detail-view', args=(str(self.id)))

MainApp/forms.py
from django import forms
from .models import Post, Notes, Course

choices = Course.objects.all().values_list('course_name', 'course_name')
choice_list = []

for item in choices:
    choice_list.append(item)



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'post_image', 'post_file')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'post_image': forms.FileInput(attrs={'class': 'form-control'}),
            'post_file': forms.FileInput(attrs={'class': 'form-control'}),

        }

class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('course', 'title', 'header_image', 'header_file', 'body')

        widgets = {
            'course': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'header_image': forms.FileInput(attrs={'class': 'form-control'}),
            'header_file': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_code', 'lecture_teacher', 'practical_teacher']
        widgets = {
            'course_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Course Name'}),
            'course_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Course Code'}),
            'lecture_teacher': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Lecture Teacher'}),
            'practical_teacher': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Practical Teacher'}),
        }

MainApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Notes, Course
from .forms import PostForm, NotesForm, CourseForm 
from django.urls import reverse_lazy


class FirstView(TemplateView):
    template_name = 'index.html'

class DashboardView(TemplateView):
    template_name = 'home.html'

class PostView(ListView):
    model = Post
    template_name = 'post.html'
    ordering = ['-post_date','-id']

class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class AddPostView(CreateView):
    model = Post
    form_class = PostForm 
    template_name = 'add_post.html'

class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'update_post.html'
#    fields = ['title', 'body']

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('post-view')





#Notes

class NotesView(ListView):
    model = Notes
    template_name = 'notes.html'
    ordering = ['-notes_date','-id']

class NotesDetailView(DetailView):
    model = Notes
    template_name = 'notes_detail.html'

class AddNotesView(CreateView):
    model = Notes
    form_class = NotesForm 
    template_name = 'add_notes.html'

class UpdateNotesView(UpdateView):
    model = Notes
    form_class = NotesForm
    template_name = 'update_notes.html'
#    fields = ['title', 'body']

class DeleteNotesView(DeleteView):
    model = Notes
    template_name = 'delete_notes.html'
    success_url = reverse_lazy('notes-view')





#COURSE
class AddCourseView(CreateView):
    model = Course
    form_class = CourseForm  # Use your custom form here
    template_name = 'add_course.html'

def course_view(request, cats):
    course_posts = Notes.objects.filter(course=cats)
    course_posts = course_posts.order_by('id')  # Order alphabetically by title
    return render(request, 'course.html', {'cats': cats, 'course_posts': course_posts})

class CourseListView(ListView):
    model = Course
    template_name = 'course_list.html'
    ordering = ['course_name']

MainApp/templates/add_notes.html
{% extends 'base/base.html' %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h4><i class="fa fa-align-justify"></i> Add Notes</h4>
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-info" >Send</button>
                <a href="{% url 'notes-view' %}" class="btn btn-success">Back</a>
                

            </form>
        </div>
    </div>

{% endblock %}

MainApp/templates/add_post.html
{% extends 'base/base.html' %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h4><i class="fa fa-align-justify"></i> Add Post</h4>
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-info" >Send</button>
                <a href="{% url 'post-view' %}" class="btn btn-success">Back</a>
                

            </form>
        </div>
    </div>

{% endblock %}

MainApp/templates/course.html
{% extends 'base/base.html' %}
{% block content %}


  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i> {{ cats }} </div>
      <div class="card-body">

            {% for notes in course_posts %}

                <a href="{% url 'notes_detail-view' notes.pk %}">{{ notes.title }} | <span style="color: red;">{{ notes.notes_date }}</span> </a>
                <hr>
            {% endfor %}
                            <a href="{% url 'course-list' %}" class="btn btn-success">
                    Back
                </a>

      </div>
  </div>

{% endblock %}

MainApp/templates/course_list.html
{% extends 'base/base.html' %}
{% block content %}


  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>Course List</div>
      <div class="card-body">
          <table class="table table-responsive-sm">
              <thead>
                  <tr>
                
                      <th>Course Name</th>
                      <th>Course Code</th>
                      <th>Lecture Teacher</th>
                      <th>Practical Teacher</th>

                  </tr>
              </thead>
              <tbody>
                  {% for course in object_list %}
                    <tr>
             
                        <td> <a href="{% url 'course-view' course.course_name %}" class="course-link">{{ course.course_name }} </a></td>
                        <td>{{ course.course_code}}</td>
                        <td>{{ course.lecture_teacher }}</td>
                        <td>{{ course.practical_teacher }}</td>
                    

                    </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>

{% endblock %}

MainApp/templates/dashboard.html
{% extends 'base.html' %}




{% block content %}
    <!-- Page content -->
    <div class="content">
        <h1 class="text-primary mb-4">Hello! Welcome to the GIS Class Management System</h1> <hr>
        
        <!-- Moving text using marquee tag -->
        <marquee>Please Login to continue. Register if you don't have an account. </marquee> <hr>

        <!-- Carousel -->
        <div id="carouselExampleInterval" class="carousel slide mt-5" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active" data-interval="10000">
              <div class="carousel-card bg-info text-white p-4 rounded"> <!-- Increased padding for larger cards -->
                <div class="card-body">
                  <h5 class="card-title">First Slide</h5>
                  <p class="card-text">This is the text content for the first slide. You can place any text here.</p>
                </div>
              </div>
            </div>
            <div class="carousel-item" data-interval="2000">
              <div class="carousel-card bg-success text-white p-4 rounded"> <!-- Increased padding for larger cards -->
                <div class="card-body">
                  <h5 class="card-title">Second Slide</h5>
                  <p class="card-text">This is the text content for the second slide. You can place any text here.</p>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <div class="carousel-card bg-warning text-dark p-4 rounded"> <!-- Increased padding for larger cards -->
                <div class="card-body">
                  <h5 class="card-title">Third Slide</h5>
                  <p class="card-text">This is the text content for the third slide. You can place any text here.</p>
                </div>
              </div>
            </div>
          </div>
        </div> <br>

        <!-- Login and Registration buttons -->
        <div class="text-center">
            <a href="{% url 'login' %}" class="btn btn-lg btn-primary mr-3">Login</a>
            <a href="{% url 'register' %}" class="btn btn-lg btn-success">Register</a>

        </div>
    </div>

{% endblock %}

MainApp/templates/delete_post.html
{% extends 'base/base.html' %}
{% block content %}


  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i> Delete: {{ post.title }} </div>
      <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <strong style="color:red;">Are you sure! 🤔</strong> <br> <br>
                <button class="btn btn-secondary" >Delete</button>
                

            </form>

      </div>
  </div>

{% endblock %}

MainApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dashboard</title>
<style>
/* CSS styles */
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;    
    font-family: Arial, sans-serif;
}

body {
    background: linear-gradient(90deg, #5D54A4, #7C78B8);       
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
}

.container {   
    background-color: #fff;
    box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.1);
    border-radius: 16px;
    overflow: hidden;
    width: 400px; /* Adjust width */
    height: 300px; /* Adjust height */
}

.dashboard__content {
    padding: 30px;
    text-align: center; /* Center align content */
}

.dashboard__title {
    font-size: 24px;
    margin-bottom: 20px;
    color: #333;
}

.dashboard__subtitle {
    font-size: 16px;
    margin-bottom: 30px;
    color: GREEN;
}

.button {
    background-color: #4C489D;
    color: #fff;
    font-size: 14px;
    padding: 10px 16px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    text-decoration: none;
    margin-right: 10px; /* Add space between buttons */
}

.button:last-child {
    margin-right: 0; /* Remove margin from the last button */
}

.button:hover {
    background-color: #6A679E;
}

.button__icon {
    margin-left: 8px;
}


</style>
</head>
<body>
<!-- HTML content -->
<div class="container">
    <div class="dashboard__content">
        <h1 class="dashboard__title">Welcome to GIS CLASS</h1>
        <p class="dashboard__subtitle">Please login or register to continue</p> <hr> <br><br><br>
        <a href="{% url 'login' %}" class="button">
            Log In Now
            <i class="button__icon fas fa-chevron-right"></i>    
        </a> 

        <a href="{% url 'register' %}" class="button">
            Register Now
            <i class="button__icon fas fa-chevron-right"></i>
        </a>
    </div>    
</div>
</body>
</html>

MainApp/templates/notes.html
{% extends 'base.html' %}


{% block content %}
    <!-- Page content -->
    <div class="content">
        <h1>All Notes</h1> <hr>
        <div class="post-list">
            {% for notes in object_list %}
            <div class="post-card">
                <a href="{% url 'notes_detail-view' notes.pk %}">
                    <h2>{{ notes.title }}</h2> <span style="color: red;">{{ notes.notes_date }}</span>

                </a>
                <hr>

            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

MainApp/templates/notes_detail.html
{% extends 'base/base.html' %}
{% block content %}


  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>{{ notes.course }} </div>
      <div class="card-body">

                <h4> {{ notes.title }} <span style="color: red;"> | {{ notes.notes_date }}</span> </h4>

                {% if user.is_cr %}
                    <a href="{% url 'update-notes' notes.pk %}">Edit</a> -
                    <a href="{% url 'delete-notes' notes.pk %}">Delete</a>
                {% endif %}
                
                <hr>
                <p>{{ notes.body|safe}}</p>


                    {% if notes.header_file %}
                        <a href="{{ notes.header_file.url }}" download>
                            <i class="fas fa-download"></i> Download File - {{ notes.header_file }}
                        </a> 
                    {% endif %}
        <br><br>

                    {% if notes.header_image %}

                        <img src="{{ notes.header_image.url }}" width="600" height="300"> <br><br>


                   {% endif %}

                <a href="{% url 'course-list' %}" class="btn btn-success">
                    Back
                </a>

      </div>
  </div>

{% endblock %}

MainApp/templates/post_detail.html
{% extends 'base/base.html' %}
{% block content %}


  <div class="card">
      <div class="card-header">
          <i class="fa fa-align-justify"></i>{{ post.title }} <span style="color: red;">{{ post.post_date }}</span>

      </div>

      <div class="card-body">

            {% if user.is_cr %}
   
                <a href="{% url 'update-post' post.pk %}">Edit</a> -
                <a href="{% url 'delete-post' post.pk %}">Delete</a>
            {% endif %}


            <hr>
            <p>{{ post.body|safe}}</p>

            {% if post.post_file %}
                <a href="{{ post.post_file.url }}" download>
                    <i class="fas fa-download"></i> Download File - {{ post.post_file }}
                </a> <br><br>
            {% endif %}

            {% if post.post_image %}

                <img src="{{ post.post_image.url }}" width="500" height="300">


            {% endif %}


            <br><br>

                <a href="{% url 'post-view' %}" class="btn btn-success">
                    Back
                </a>

      </div>

  </div>

{% endblock %}

MainApp/templates/sidebar.html
<div class="sidebar">
    <a href="{% url 'dashboard' %}">Home</a>
    <a href="#">About</a>
    <a href="#">Services</a>
    <a href="#">Contact</a>
{% if user.is_authenticated %}
    <a href="{% url 'course-list' %}">Courses</a>
    <a href="{% url 'post-view' %}">Posts</a>

    {% if user.is_cr %}
         <a href="{% url 'add-notes' %}">Add Notes</a>
         <a href="{% url 'add-post' %}">Add Post</a>
         <a href="{% url 'user_list' %}">Users</a>
    {% endif %}


  


    {% if user.is_admin %} 
        <a href="{% url 'add-course' %}">Add Course</a>
        <a href="admin">Admin Panel</a>
    {% endif %} 

    
{% endif %}
</div>

MainApp/templates/update_notes.html
{% extends 'base/base.html' %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h4><i class="fa fa-align-justify"></i> Update Notes</h4>
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-info" >Update</button>
                

            </form>
        </div>
    </div>

{% endblock %}

MainApp/templates/update_post.html
{% extends 'base/base.html' %}
{% block content %}

    <div class="card">
        <div class="card-header">
            <h4><i class="fa fa-align-justify"></i> Update Post</h4>
        </div>
        <div class="card-body">
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-info" >Update</button>
                

            </form>
        </div>
    </div>

{% endblock %}

MainApp/templates/user_list.html
{% extends 'base.html' %}



{% block content %}
    <!-- Page content -->
    <div class="content">
        <h1 class="text-primary mb-4">Admin {{ user.username|upper }} Here are registered users</h1> <hr>
        <ul>
                 <li><a href="admin/ClassAccountApp/user/">{{ user.username }}</a></li>
      

        </ul>

           
    </div>

{% endblock %}